import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "@/features/errors/ErrorBoundary";
import { ContextDataProvider } from "@/services/ContextData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContextDataProvider>
      <ErrorBoundary><html lang="en">
        <body className={inter.className}>{children}</body>
      </html></ErrorBoundary>
    </ContextDataProvider>
  );
}
